config/routes.rb
Bitebuddy::Application.routes.draw do

  get "home",    to: "pages#home",      as: "home"
  get "inside",  to: "pages#inside",    as: "inside"
  get "about",   to: "pages#about",     as: "about"
  get "contact", to: "pages#contact",   as: "contact"
  get "terms",   to: "pages#terms",     as: "terms"
    
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources  :users
  resources  :menu_items

  namespace :admin do
    root "base#index"
    resources :users
  end

  authenticated do
    root to: 'menu_items#menu', as: :authenticated
  end

  root "pages#home"
  
end

app/models/menu_item.rb
# t.integer   :user_id
# t.string    :title,         null: false, default: ""
# t.string    :description,   null: false, default: ""
# t.integer   :quantity,      null: false, default: 1
# t.integer   :orders_count,  null: false, default: 0
# t.boolean   :same_day,      null: false, default: false
# t.boolean   :expired,       null: false, default: false
# t.decimal   :minimum_tip,   null: false, default: 5.0, precision: 4, scale: 2
# t.integer   :freshness,     null: false, default: 0
# t.datetime  :expiry_time

class MenuItem < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable_on :ingredients, :allergens, :paybacks
  before_save :title_capitalize # Figure how to pass arguments

  ALLERGENS       = ['Fruit', 'Milk', 'Oats', 'Soy', 'Wheat', 'Eggs', 'Peanuts', 'Tree nut', 
                     'Meat', 'Fish', 'Shellfish', 'Garlic', 'Gluten', 'Sulfites', 'None of the above']
  PAYBACK_METHODS = ['Tipping', 'Chatting', 'A drink', "Any gift but alcohol", 'Just a thank you']

  scope :sorted_down_by_update_date, -> { order('updated_at DESC') }

  # Pagination
  paginates_per 20

  # Paperclip
  has_attached_file :menu_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/menu_items/:style/missing.png"
  validates_attachment_content_type :menu_image, content_type: /\Aimage\/.*\Z/  
  
  # Validations
  validates :user_id, presence: :true
  validates :title, presence: true,
                    length: { minimum: 5, maximum: 140}
  validates :description, length: { maximum: 255}
  validates :quantity,  presence: :true,
                        numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :same_day, inclusion: [true, false]
  validates :minimum_tip, numericality: { greater_than_or_equal_to: 5.0 }
  validates :freshness, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :expired,  inclusion: [true, false]
  validates :expiry_time, presence: :true,
                          timeliness: { on_or_after: -> { 1.day.from_now }, before: -> { 31.days.from_now }, type: :date }
  validate  :amount_of_ingredients
  validate  :grattitude

  # Capitalize titles with right punctuation.
  def title_capitalize 
  # Move constants to an external text file
  # Change method back to handling aruments
    no_caps = ["a", "an", "and", "abaft", "aboard", "about", "above", "absent", "across", "afore", "after", "against",
               "along", "alongside", "amid", "amidst", "among", "amongst", "an", "anenst", "apropos", "apud", "around",
               "as", "aside", "astride", "at", "athwart", "atop", "barring", "before", "behind", "below", "beneath", "beside",
               "besides", "between", "beyond", "but", "by", "circa", "concerning", "despite", "down", "during", "except", "excluding",
               "failing", "following", "for", "forenenst", "from", "given", "in", "including", "inside", "into", "la", "like", "mid",
               "midst", "minus", "modulo", "near", "next", "notwithstanding", "o", "of", "off", "on", "onto", "opposite", "or",
               "out", "outside", "over", "pace", "past", "per", "plus", "pro", "qua", "regarding", "round", "sans", "save",
               "since", "than", "the", "through", "thru", "throughout", "thruout", "till", "times", "to", "toward", "towards",
               "under", "underneath", "unlike", "until", "unto", "up", "upon", "versus", "vs.", "v.", "via", "vice", "vis-à-vis",
               "with", "within", "without"]
    delimiters = [".", ". ", "?", "? ", "!", "! ", "...", "... "]
    ary = self.attributes['title'].split(/\b/)
    ary.each_with_index do |word, index|
        word.capitalize! if delimiters.include? ary[index-1]
        word.capitalize! unless no_caps.include? word
        word.downcase! if ary[index-1] == "'"
    end
    self.title = ary.join
  end 
  
  private

    def amount_of_ingredients
      number_of_ingredients = ingredient_list.length
      errors.add(:ingredient_list, "should include 2 or more main ingredients") if number_of_ingredients < 2
      errors.add(:ingredient_list, "should not include more than 8 main ingredients") if number_of_ingredients > 8
    end

    def grattitude
      number_of_payback_methods = payback_list.length
      errors.add(:payback_list, "should include at least 2 acceptable forms of grattitude") if number_of_payback_methods < 2
    end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy] 

  def menu
    # This is a temporary check until working with pagination and infinite scrolling
    @menu_items = MenuItem.sorted_down_by_update_date.page(params[:page])     
  end 

  def show
    @menu_item = MenuItem.find(params[:id])
    respond_to do |format|
        format.html { render 'modal' }
        format.js
    end
  end

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = current_user.menu_items.build(menu_item_params)
    if @menu_item.save      
      flash[:notice] = "#{@menu_item.title} is added to the menu"
    else
      render 'new'
    end
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    @menu_item = MenuItem.find(params[:id])  
    @menu_item.update_attributes(menu_item_params)  
    respond_to do |format|
      if @menu_item.save
        format.html { flash.now[:notice] = "#{@menu_item.title} is updated"; render 'show' }
        format.json { respond_with_bip(@menu_item) }
      else
        format.html { render "edit" }
        format.json { respond_with_bip(@menu_item) }
      end
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])
    @menu_item.destroy
    flash[:notice] = "Menu item deleted"
    redirect_to root_path
  end

  private

    def menu_item_params
      params.require(:menu_item).permit(:title, :description, :expiry_time, :quantity, :same_day, :ingredient_list, :menu_image, { allergen_list: [], payback_list: [] })
    end

    def correct_user
      @menu_item = current_user.menu_items.find_by_id(params[:id])
      redirect_to root_url if @menu_item.nil?
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_menu_item.html.erb
<!-- Including a DIV (block element) inside of an ANCHOR (inline element) is not considered best practice; Research ways to use JavaScript to convert entire DIV into a clickable link with remote: :true -->

<div class="item">
<%= link_to menu_item_path(menu_item.id), remote: true, class: 'box', data: { toggle: 'modal', target: '#menuItemModal' } do %>

<div>
  <%= image_tag(menu_item.menu_image.url(:medium)) %>

  <h4><%= menu_item.title %></h4>

  <p><%= menu_item.description %></p>

  <% if menu_item.user == current_user %>
    <p>
      <%= link_to raw('<i class="fa fa-pencil-square-o"></i>&nbsp; Edit'), edit_menu_item_path(menu_item),
                                                                            class: 'btn btn-xs btn-success' %>
      <%= link_to raw('<i class="fa fa-trash-o"></i>&nbsp; Delete'), menu_item, method: :delete,
                                            data: { confirm: 'You sure?' }, class: 'btn btn-xs btn-danger' %>
    </p>
  <% end %>
</div>

<% end %>

  <p class="<%= 'hidden' if menu_item.user == current_user %>">
    by <%= link_to menu_item.user.name, user_path(menu_item.user), class: 'to-user' %>
  </p>

</div>

app/views/menu_items/_menu_item_form.html.erb
<%= error_messages_for @menu_item %>
<%= form_for(@menu_item) do |f| %>

  <div class="form-group">
    <%= f.label :title %>     
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :menu_image, 'Picture' %>     
    <%= f.file_field :menu_image, class: "input-group" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>     
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :ingredient_list, 'Main ingredients' %> <i><small>(the meats, the veggies... etc. at least 2, comma separated)</small></i> 
    <%= f.text_area :ingredient_list, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :quantity, 'The following quantity will be available' %>     
    <%= f.text_field :quantity, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :allergen_list, 'Allergy notice' %> <i><small>(be responsible and notify people with common allergies)</small></i>
    <ul class="list-inline group-checkbox">
      <% MenuItem::ALLERGENS.each do |allergen| %>
        <li>
          <div class="checkbox">
            <%= f.check_box :allergen_list, { multiple: true }, allergen, nil %><label for="menu_item_allergen_list_<%= "#{allergen.downcase.tr(" ", "_")}" %>"><%= "#{allergen}" %></label>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

 <div class="form-group">
    <%= f.label :payback_list, 'How do you expect to be appreciated?' %> <i><small>(choose at least two accepted forms of gratitude)</small></i>
    <ul class="list-inline group-checkbox">
      <% MenuItem::PAYBACK_METHODS.each do |payback_method| %>
        <li>
          <div class="checkbox">                       
            <%= f.check_box :payback_list, { multiple: true }, payback_method, nil %><label for="menu_item_payback_list_<%= "#{payback_method.downcase.tr(" ", "_")}" %>"><%= "#{payback_method}" %></label> 
          </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="form-group">
    <%= f.label :same_day, 'Feels like a super chef?' %>
    <div class="checkbox">
      <%= f.check_box :same_day %> <%= f.label :same_day, "This item can be offered on the same day." %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :expiry_time %>     
    <%= f.datetime_select :expiry_time, class: "form-control" %>
  </div>

  <%= f.submit "submit", class: "btn btn-success" %> &nbsp; <%= link_to "Cancel", root_path, class: "btn btn-primary" %> 
<% end %>

app/views/menu_items/_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="menuItemModalLabel">
        <%= best_in_place_if owner?(@menu_item), @menu_item, :title %>
      </h4>
    </div>
    <div class="modal-body">
      <p><%= best_in_place_if owner?(@menu_item), @menu_item, :description, type: :textarea %></p> 
      <p><%= best_in_place_if owner?(@menu_item), @menu_item, :ingredient_list %></p>
      <p><%= @menu_item.allergen_list.each { |allergen| allergen + ', ' } %></p> 
      <p><%= @menu_item.payback_list.each { |allergen| allergen + ', ' } %></p> 
      <p>Same day? <b><i><%= best_in_place_if owner?(@menu_item), @menu_item, :same_day, type: :checkbox %></i></b></p>
      <p><%= best_in_place_if owner?(@menu_item), @menu_item, :expiry_time, type: :date %></p> 
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="button" class="btn btn-primary">Save changes</button>
    </div>
  </div>
</div>

app/views/menu_items/create.html.erb
<h1>MenuItems#create</h1>
<p>Find me in app/views/menu_items/create.html.erb</p>

app/views/menu_items/destroy.html.erb
<h1>MenuItems#destroy</h1>
<p>Find me in app/views/menu_items/destroy.html.erb</p>

app/views/menu_items/edit.html.erb
<% provide(:title, "Edit Menu Item") %>

<div class="wrap">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 left-box">
        <div class="container">
          <h1>Edit Menu item</h1>
          <%= render 'menu_item_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu_items/menu.html.erb
<% provide(:title, "Menu") %>
<div class="row">
  <div class="col-xs-12">
    <div class="masonry-parent">
    <h1>Today's Menu</h1>
    <div id="masonry-container" class="masonry clearfix">
    <%= render @menu_items %>
    </div>
  </div>
</div>

<div class="modal" id="menuItemModal" tabindex="-1" role="dialog" aria-labelledby="menuItemModalLabel" aria-hidden="true"></div>
<div class="hidden"><%= paginate @menu_items -%></div>

app/views/menu_items/menu.js.erb
$("#masonry-container").append("<%= escape_javascript(render @menu_items) %>");

app/views/menu_items/new.html.erb
<% provide(:title, "New Menu Item") %>

<div class="wrap">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-md-offset-2 col-lg-offset-2 left-box">
        <div class="container">
          <h1>Create a new menu item</h1>
          <%= render 'menu_item_form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu_items/show.html.erb
<%= image_tag @menu_item.menu_image.url(:medium) %>
<h1>
  <%= @menu_item.title %>
  <% if @menu_item.user == current_user %>
  | <small>
  <%= link_to 'Edit', edit_menu_item_path %>
  </small>
  <% end %>
</h1>

app/views/menu_items/show.js.erb
$("#menuItemModal").html("<%= escape_javascript(render 'modal') %>");
$('#menuItemModal').modal('show');

app/views/menu_items/update.html.erb
<h1>MenuItems#update</h1>
<p>Find me in app/views/menu_items/update.html.erb</p>