config/routes.rb
Bitebuddy::Application.routes.draw do

  get "home",    to: "pages#home",      as: "home"
  get "inside",  to: "pages#inside",    as: "inside"
  get "about",   to: "pages#about",     as: "about"
  get "contact", to: "pages#contact",   as: "contact"
  get "terms",   to: "pages#terms",     as: "terms"
    
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources  :users
  resources  :menu_items

  namespace :admin do
    root "base#index"
    resources :users
  end

  authenticated do
    root to: 'menu_items#menu', as: :authenticated
  end

  root "pages#home"
  
end

app/models/user.rb
# t.string   :username,           null: false, default: ""
# t.string   :email,              null: false, default: ""
# t.string   :encrypted_password, null: false, default: ""
# t.string   :name,               null: false, default: ""
# t.boolean  :admin,              null: false, default: false
# t.boolean  :locked,             null: false, default: false
# t.string   :slug
# t.string   :reset_password_token
# t.datetime :reset_password_sent_at
# t.datetime :remember_created_at
# t.integer  :sign_in_count,      null: false, default: 0
# t.datetime :current_sign_in_at
# t.datetime :last_sign_in_at
# t.string   :current_sign_in_ip
# t.string   :last_sign_in_ip

class User < ActiveRecord::Base
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile
  before_create :create_profile

  has_many :menu_items, dependent: :destroy
  
  attr_accessor :login

  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # Pagination
  paginates_per 100
  
  # Validations

  # :name
  validates :name, presence: true
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..18 }
  before_save { username.downcase! }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  before_save { email.downcase! }
 
  
  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end
  
  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end
  
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end
  
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end
  
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


  # # Find a way to notify for profile completeness 
  # def profile_complete?
  #   sum = 0
  #   attributes = [self.profile.name, self.profile.birthday, self.profile.restrictions, self.profile.phone, self.profile.address, self.profile.about, self.profile.avatar]
  #   attributes.each do |attribute|
  #     sum += 1 if attribute.blank? # || "default.jpg"
  #   end
  #   sum > 2 ? false : true
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]
  

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end
  
  def show
    redirect_to edit_admin_user_path(params[:id])
  end
  
  def edit
  end
  
  def update
    old_username = @user.username
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip
    
    @user.username = new_params[:username]
    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0
    
    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end
    
    if @user.valid?
      @user.save
      redirect_to admin_users_path, notice: "#{@user.username} updated."
    else
      flash[:alert] = "#{old_username} couldn't be updated."
      render :edit
    end
  end
  
  
  private 
  
  def set_user
    @user = User.friendly.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end
  
  def user_params
    params.require(:user).permit(
    :name,
    :username,
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked,
    profile_attributes: [:id, :user_id, :birthday, :phone, :address, :about, :restrictions, :avatar]
    )
  end
  
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # def new
  #   super
  # end

  # def create
  #   super    
  # end

  # def destroy
  #   super
  # end

  def update
    @user = User.find(current_user.id)

    successfully_updated = if needs_password?(@user, params)
      @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
    else
      # remove the virtual current_password attribute
      # update_without_password doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    end

    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  private

    # check if we need password to update user data
    # ie if password or email was changed
    # extend this as needed
    def needs_password?(user, params)
      user.email != params[:user][:email] ||
        params[:user][:password].present?
  end

    # Redirects on successful sign up
    def after_sign_up_path_for(resource)
      edit_user_registration_path
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super    
  end

  def destroy
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :destroy]
  before_filter :require_admin!, only: [:destroy]

  layout 'show_profile_layout', only: [:show]

  def index
  end

  def show
    @user = User.friendly.find(params[:id])
    @user_menu_items = @user.menu_items.sorted_down_by_update_date
  end

  # def destroy
  #   User.find(params[:id]).destroy
  #   flash[:notice] = "User deleted"
  #   redirect_to root_url    
  # end

  private
  
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="wrap">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-5 left-box">
        <div class="container">
          <h1>
            Edit User <small><%= "#{@user.username} - id: #{@user.id}" %></small>
          </h1>
          <p><%= link_to "Back to Users", admin_users_path %></p>

          <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>
          
          <div class="form-group">
            <%= f.label :username %>
            <%= f.text_field :username, :autofocus => true, class: "form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>  
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
          
          <% unless current_user.id == @user.id %>

            <div class="checkbox">
              <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
            </div>
          
            <div class="checkbox">
              <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
            </div>

          <% end %>

          <%= f.submit "Update User", class: "btn btn-success" %>
              
          <% end %>
        </div>
      </div>

      <div class="col-sm-12 col-md-7 left-box">
        <div class="container">

          <h1>Profile Details</h1>
          <ul>
            <li><%= "#{@user.profile.birthday}" %></li>
            <li><%= "#{@user.profile.phone}" %></li>
            <li><%= "#{@user.profile.address}" %></li>
            <li><%= "#{@user.profile.about}" %></li>
            <li><%= "#{@user.profile.restrictions}" %></li>
          </ul>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="wrap">
  <div class="container">
    <div class="row">
      <div class="col-md-12 left-box">
        <div class="container">
          <h1>Users <small>Admin</small></h1>
          <p><%= link_to "Back to Admin", admin_root_path %></p>

          <div class="text-center">
            <p><%= page_entries_info @users %></p>
            <%= paginate @users %>
          </div>

          <%= form_tag admin_users_path, method: 'get', html: {class: 'form-inline', role: "form"} do %>
            <p>
              <div class="form-group">
                <%= text_field_tag :search, params[:search], class: "form-control", placeholder: 'Search users' %>
                <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
                <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
              </div>
            </p>
          <% end %>

          <div class="table-responsive">
            <table class="table table-hover">
              <tr>
                <th>User ID</th>
                <th>Username</th>
                <th>Admin</th>
                <th>Locked</th>
                <th>Email</th>
                <th>Sign In Count</th>
                <th>Created At</th>
                <th>Last Sign In</th>
                <th>Last Sign In IP</th>
              </tr>
              
              <% @users.each do |user| %>
              
              <tr>
                <td><%= user.id %></td>
                <td><%= link_to user.username.capitalize, admin_user_path(user) %></td>
                <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
                <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
                <td><%= user.email %></td>
                <td><%= user.sign_in_count %></td>
                <td><%= time_ago_in_words(user.created_at) %></td>
                <% unless user.last_sign_in_at.nil? %>
                <td><%= time_ago_in_words(user.last_sign_in_at)%> ago</td>
                <% else %>
                <td>never</td>
                <% end %>
                <td><%= user.last_sign_in_ip %></td>
              </tr>
              
              <% end %>
              
            </table>
          </div>

          <div class="text-center">
            <p><%= page_entries_info @users %></p>
            <%= paginate @users %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  