config/routes.rb
Bitebuddy::Application.routes.draw do

  get "home",    to: "pages#home",      as: "home"
  get "inside",  to: "pages#inside",    as: "inside"
  get "about",   to: "pages#about",     as: "about"
  get "contact", to: "pages#contact",   as: "contact"
  get "terms",   to: "pages#terms",     as: "terms"
    
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources  :users
  resources  :menu_items

  namespace :admin do
    root "base#index"
    resources :users
  end

  authenticated do
    root to: 'menu_items#menu', as: :authenticated
  end

  root "pages#home"
  
end

app/views/layouts/_footer.html.erb
<% unless user_signed_in? %>  
  <div id="footer">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Us",   about_path    %></li>
        <li><%= link_to "Terms",      terms_path    %></li>
        <li><%= link_to "Contact Us", contact_path  %></li>
        <li><%= link_to "Blog",       '#'           %></li>
        <!-- <li>&copy; 2014 BiteBuddy</li>  -->
      </ul>
    </div>
  </div>
<% end %>  

app/views/layouts/_html_head.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!-- This loads very slowly, research ways to speed up asset delivery, and drop unused code -->
</head>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("bitebuddy.png", alt: "Bite Buddy", class: "navbar-brand"), root_path, "data-no-turbolink" => true) %>
    </div>
    <div class="collapse navbar-collapse navbar-right">      
        <%= render 'layouts/navigation_links' %>      
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>

  <%= form_for(resource, as: resource_name, 
                         url: session_path(resource_name), 
                         html: {class: 'form-inline'},
                         role: "form") do |f| %>

    <div class="form-group">
      <%= f.text_field :login, class: "form-control", placeholder: 'Username or email' %>  
    </div>
    
    <div class="form-group">      
      <%= f.password_field :password, class: "form-control", placeholder: 'Enter your password' %>
    </div>      

      <div class="form-group">
        <div class="checkbox">
          <%= f.check_box :remember_me %> <%= f.label :remember_me %>
        </div><br/>      
        <%= link_to "Forgot your password?", new_password_path(resource_name) %>
        &nbsp;
      </div>

    <%= f.submit "Sign in", class: "btn btn-success" %>

  <% end %>

<% else %>
  <ul class="nav navbar-nav">
    <li><%= link_to current_user.name, current_user %></li>
    <li><%= link_to "Menu", root_path %></li>
    <li><%= link_to "Add a Menu Item", new_menu_item_path %></li>
    <li><%= link_to "People", users_path %></li>
    <li><%= link_to "Edit Account", edit_user_registration_path %></li>
        

    <% if current_user.admin? %>
      <li><%= link_to "Admin Home", admin_root_path %></li>
    <% end %>

    <li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
  </ul>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/html_head' %>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

    <div class="col-sm-6 col-sm-offset-3 text-center">
      <%= render 'layouts/messages' %>
    </div>

  <%= yield %>


  <%= render 'layouts/footer' %>


</body>
</html>

app/views/layouts/show_profile_layout.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/html_head' %>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <%= yield %>

</body>
</html>